userId: userId
apiKey: apiKey
apiSecret: secret

server:
  port: 8090
  
com:
  auth0:
    domain: user-acess.auth0.com
    clientId: Fv77Jp1j2mi19_5dsb3eLa87v8-HQOFX
    clientSecret: xspSkAVMqs3O4Wn2Ro2cYN25a3cFtjkfnYVsrUMEAafRkeFE8rQJ2AZ56afJbMoZ